#!/usr/bin/python
# -*- coding: utf-8 -*-
environ = {
    'wsgi.errors': '<<<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f24892e1910>>>',
    'wsgi.version': (1, 0),
    'wsgi.multithread': False,
    'wsgi.multiprocess': False,
    'wsgi.run_once': False,
    'wsgi.file_wrapper': "<<<class 'gunicorn.http.wsgi.FileWrapper'>>>",
    'wsgi.input_terminated': True,
    'SERVER_SOFTWARE': 'gunicorn/19.10.0',
    'wsgi.input': '<<<gunicorn.http.body.Body object at 0x7f24892e1890>>>',
    'gunicorn.socket': "<<<socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8888), raddr=('127.0.0.1', 59730)>>>",
    'REQUEST_METHOD': 'GET',
    'QUERY_STRING': '',
    'RAW_URI': '/homework',
    'SERVER_PROTOCOL': 'HTTP/1.1',
    'HTTP_HOST': '127.0.0.1:8889',
    'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0',
    'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'HTTP_ACCEPT_LANGUAGE': 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3',
    'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
    'HTTP_CONNECTION': 'keep-alive',
    'HTTP_COOKIE': 'auth.strategy=local; auth._token.local=Bearer%20eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJ1c2VybmFtZSI6ImV3ZW4tbGUtYmloYW4iLCJpYXQiOjE1ODcyMDE5OTEsImV4cCI6MTU4NzI0NTE5MSwib3JpZ19pYXQiOjE1ODcyMDE5OTF9.M4o_eiWxIwRviYnBGbyOnc4vG6ZSq64TAC2rgDdzhQI; auth._refresh_token.local=false',
    'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
    'HTTP_CACHE_CONTROL': 'max-age=0',
    'wsgi.url_scheme': 'http',
    'REMOTE_ADDR': '127.0.0.1',
    'REMOTE_PORT': '59730',
    'SERVER_NAME': '127.0.0.1',
    'SERVER_PORT': '8888',
    'PATH_INFO': '/homework',
    'SCRIPT_NAME': '',
    }
